### ISSUE TITLE
Missing slot list in languages other than [en]

### ISSUE THREAD

**Issue by ddppddpp** [home-assistant/hassil#186]
I'm trying to add localization for homeassistant_HassRespond for my language (Bulgarian) following the [tutorial](https://github.com/home-assistant/intents/blob/main/docs/codespace/README.md).
My tests fail with the error ``` hassil.errors.MissingListError: Missing slot list { response }```.  for the following test item:
```
tests:
  - sentences:
      - "say I'm a little teapot"
    intent:
      name: HassRespond
      slots:
        response: "I'm a little teapot"
    response: "I'm a little teapot"

```
I copy-pasted the original english sentence and test into the translated file but the error persists.
I found a similar issue reported in the [communities](https://community.home-assistant.io/t/missing-slots-error-when-adding-a-sentence-in-a-different-language/630556) where the OP managed to solve it by changing the slot name (possibly avoiding a scope error), however chaning {response} to {my_response_slot} didn't solve the issue for me.
How do I troubleshoot it further and is it ok to delete the failing test scenario and submit a PR with the remaining translations?
