### ISSUE TITLE
Wildcard capitalization issues during recognition

### ISSUE THREAD

**Issue by tetele** [home-assistant/hassil#84]
Fixtures:
```
entities:
  - name: "Joseph"
    id: "person.jospeh"
    state: "home"
  - name: "Ada"
    id: "person.ada"
    state: "Work"
  - name: "John"
    id: "person.john"
    state: "not_home"
```

Sentences and tests:
```
lists:
  zone:
    wildcard: true
intents:
  HassGetState:
    data:
      - sentences:
          - "is anyone [<in>] [the] {zone:state}"
        response: any
        slots:
          domain: person
tests:
  - sentences:
      - "is anyone at Work"
    intent:
      name: HassGetState
      slots:
        domain: person
        state: Work
    response: "Yes, Ada"
```

produces

```
E                           AssertionError: Expected work, got Work for slot state for: is anyone at Work
E                           assert 'Work' == 'work'
E                             - work
E                             ? ^
E                             + Work
E                             ? ^

tests/test_language_sentences.py:143: AssertionError
```
