### ISSUE TITLE
Wildcard used as last thing in a permutation greedily grabs everything

### ISSUE THREAD

**Issue by tetele** [home-assistant/hassil#87]
```yaml
# sentences/ro/person_HassGetSate.yaml
language: ro
intents:
  HassGetState:
    data:
      - sentences:
          - "(<name>;<este> [<la>] {zone:state})"
        response: someone_yesno
        requires_context:
          domain: person
        slots:
          domain: person
```

```yaml
# tests/ro/_fixtures.yaml
language: ro
entities:
  - name: "Claudiu"
    id: "person.claudiu"
    state:
      in: "Plecat"
      out: "not_home"
    attributes:
      untranslated_state: "not_home"
```

```
@tetele ➜ /workspaces/intents (ro-untranslated-state ✗) $ python3 -m script.intentfest parse --language ro --sentence 'Claudiu este la magazin'
{
  "text": "Claudiu este la magazin",
  "match": true,
  "intent": "HassGetState",
  "slots": {
    "name": "Claudiu",
    "state": "magazin",
    "domain": "person"
  },
  "context": {
    "domain": "person",
    "untranslated_state": "not_home"
  },
  "response_key": "someone_yesno",
  "response": "Nu, ci Plecat"
}
@tetele ➜ /workspaces/intents (ro-untranslated-state ✗) $ python3 -m script.intentfest parse --language ro --sentence 'este la magazin Claudiu'
No language set, so cannot convert brightness digits to words
No language set, so cannot convert brightness digits to words
{
  "text": "este la magazin Claudiu",
  "match": false
}
```
