### ISSUE TITLE
New feature - match regex

### ISSUE THREAD

**Issue by tetele** [home-assistant/hassil#95]
It would be useful to have a special list type for matching regular expressions. For example:

```yaml
lists:
  date:
    regex: "([0-9]{0,2})[\.\/]([0-9]{0,2})[\.\/]([0-9]{4})"
```

The matched slot object should also return captured groups for subsequent use.
