### ISSUE TITLE
New feature - match sentence

### ISSUE THREAD

**Issue by tetele** [home-assistant/hassil#96]
Consider the following sentence: `turn off the lights and close the blinds`.

This sentence could be matched with `{sentence1} and {sentence2}` where both sentences are defined as wildcards, but if either sentence contains an `and`, the actual split may not work properly. More over, there's not guarantee that either sentence defined as a `wildcard` will be interpretable as a sentence in the end.

It would be useful to have a special kind of list that only matches sentences, such as:
```yaml
lists:
  sentence1:
    sentence: true
  sentence2:
    sentence: true

intents:
  And:
    data:
      - sentences:
          - "{sentence1} and[ then] {sentence2}"
```
