### ISSUE TITLE
RangeSlotList "No language set" warnings because of missing params

### ISSUE THREAD

**Issue by Nerivec** [home-assistant/hassil#97]
I've been getting quite a few of these with my [custom intents](https://github.com/Nerivec/SmartHomeEnhanced/tree/main/VoiceIntents/custom_sentences/en).

I only just started reading this codebase, but it seems to be because [HA core here](https://github.com/home-assistant/core/blob/890615bb92e8ed43f8f1053d116722ff946c7057/homeassistant/components/conversation/default_agent.py#L290) doesn't pass the `language` param, which means it [relies on](https://github.com/home-assistant/hassil/blob/55cd107c008e0269e5e005cacef25afd389b0957/hassil/recognize.py#L1139) `words_language` param for `RangeSlotList` > `words` logic. But since all four properties (see diff below) aren't added in the parsing of slot lists, it fails [here](https://github.com/home-assistant/hassil/blob/55cd107c008e0269e5e005cacef25afd389b0957/hassil/recognize.py#L1180), and logs-a-lot...

```diff
--- a/hassil/intents.py
+++ b/hassil/intents.py
@@ -362,6 +362,10 @@ def _parse_list(
             start=int(range_dict["from"]),
             stop=int(range_dict["to"]),
             step=int(range_dict.get("step", 1)),
+            digits=bool(range_dict.get("digits", True)),
+            words=bool(range_dict.get("words", True)),
+            words_language=range_dict.get("words_language"),
+            words_ruleset=range_dict.get("words_ruleset"),
         )
 
     if list_dict.get("wildcard", False):
```

If that's on purpose (because of poor performance with large ranges atm), maybe an automatic bypass of `words=True` if the range is too great could be added in the code, this way these missing params could be introduced? This would allow small ranges like hours, minutes, seconds to work without having to resort to workarounds like `({spelled_numbers:hours}|{hours})`.

Also, maybe use `intents.language` instead of passing an extra `language` param in `recognize`/`recognize_all` functions that doesn't seem to be used (neither by HA or hassil script)? Seems redundant in any case.

**Comment by Nerivec** [comment]
Simple example:

```yaml
language: "en"
intents:
  Calculate:
    data:
      - sentences:
          - "(calc[ulate]|compute|count) {x} {operator} {y}"
      - sentences:
          - "add {x} (+|plus|to) {y}"
        slots:
          operator: "+"
      - sentences:
          - "subtract {x} (-|minus) {y}"
          - "subtract {y} from {x}"
        slots:
          operator: "-"
      - sentences:
          - "multiply {x} by {y}"
        slots:
          operator: "*"
      - sentences:
          - "divide {x} by {y}"
        slots:
          operator: "/"
lists:
  operator:
    values:
      - in: "(+|plus)"
        out: "+"
      - in: "(-|minus)"
        out: "-"
      - in: "(*|times)"
        out: "*"
      - in: "(/|divided by)"
        out: "/"
  x:
    range:
      from: -15000
      to: 15000
      digits: true
      words: true
      words_language: "en"
  y:
    range:
      from: -15000
      to: 15000
      digits: true
      words: true
      words_language: "en"
```

Matches:
```bash
calc 1 + 2
```

Doesn't match:
```bash
calc 1 + two
```
