### ISSUE TITLE
Having a wildcard at the end of sentence creates weird results

### ISSUE THREAD

**Issue by salleq** [home-assistant/hassil#98]
```YAML
#tests #1
language: fi
tests:
  - sentences:
      - laita omena minun ostoslistalleni
      - laita omena listalle
      - lisää omena ostoslistalle
# Below sentences create an error
      - lisää mun ostoslistalle omena
      - laita miun ostoslistalle omena

    intent:
      name: HassShoppingListAddItem
      slots:
        item: "omena "
    response: "omena lisätty"
```
``` YAML
#sentence
language: "fi"
intents:
  HassShoppingListAddItem:
    data:
      - sentences:
          - (lisää|laita) <item> <my_list>
          - (lisää|laita) <my_list> <item>
        response: item_added
        expansion_rules:
          my_list: "[minun|mun|miun] [ostos]lista[lle|lleni|llemme] "
          item: "{shopping_list_item:item}"
```
This is the error I get when running tests with:
```BASH
pytest tests --language fi -k HassShoppingListAdd
```
```PYTHON
E                           AssertionError: Expected omena, got omena  for slot item for: lisää mun ostoslistalle omena
E                           assert 'omena ' == 'omena'
E                             - omena
E                             + omena 
E                             ?      +
```

I would expect all test go through, but the sentences where the word "omena" ("apple") is last, it needs to be added without the whitespace at end. The below works:

```YAML
#tests #2
language: fi
tests:
  - sentences:
      - laita omena minun ostoslistalleni
      - laita omena listalle
      - lisää omena ostoslistalle

    intent:
      name: HassShoppingListAddItem
      slots:
        item: "omena "
    response: "omena lisätty"

  # Below sentences only work when the item is given without the whitespace in the end.
  - sentences:
      - lisää mun ostoslistalle omena
      - laita miun ostoslistalle omena

    intent:
      name: HassShoppingListAddItem
      slots:
        item: "omena"
    response: "omena lisätty"
```
